// src/frontend/vue/components/Image.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import {
  buildOptimizedUrl,
  generateSrcSet,
  generateBlurSvg,
  DEFAULT_QUALITY,
} from "../../shared/imageUtils";

type ImageProps = {
  src: string;
  alt: string;
  width?: number;
  height?: number;
  fill?: boolean;
  quality?: number;
  sizes?: string;
  unoptimized?: boolean;
  loading?: "lazy" | "eager";
  priority?: boolean;
  placeholder?: "blur" | "empty" | string;
  blurDataURL?: string;
  className?: string;
};

const props = withDefaults(defineProps<ImageProps>(), {
  quality: DEFAULT_QUALITY,
  loading: "lazy",
});

const blurRemoved = ref(false);

const resolvedSrc = computed(() => {
  if (props.unoptimized) return props.src;
  if (!props.width) return buildOptimizedUrl(props.src, 0, props.quality);

  return buildOptimizedUrl(props.src, props.width, props.quality);
});

const srcSet = computed(() =>
  props.unoptimized
    ? undefined
    : generateSrcSet(props.src, props.width, props.sizes, undefined, undefined),
);

const resolvedSizes = computed(
  () => props.sizes ?? (props.fill ? "100vw" : undefined),
);
const resolvedLoading = computed(() =>
  props.priority ? "eager" : props.loading,
);
const resolvedFetchPriority = computed(() =>
  props.priority ? "high" : undefined,
);

const hasBlur = computed(
  () =>
    props.placeholder === "blur" ||
    (typeof props.placeholder === "string" &&
      props.placeholder !== "empty" &&
      props.placeholder.startsWith("data:")),
);

const blurBackground = computed(() => {
  if (!hasBlur.value || blurRemoved.value) return undefined;
  if (
    typeof props.placeholder === "string" &&
    props.placeholder !== "blur" &&
    props.placeholder.startsWith("data:")
  ) {
    return generateBlurSvg(props.placeholder);
  }
  if (props.blurDataURL) return generateBlurSvg(props.blurDataURL);

  return undefined;
});

const imgStyle = computed(() => {
  const base: Record<string, string | number> = { color: "transparent" };
  if (blurBackground.value) {
    base.backgroundImage = blurBackground.value;
    base.backgroundSize = "cover";
    base.backgroundPosition = "center";
    base.backgroundRepeat = "no-repeat";
  }
  if (props.fill) {
    base.height = "100%";
    base.inset = "0";
    base.objectFit = "cover";
    base.position = "absolute";
    base.width = "100%";
  }

  return base;
});

const handleLoad = () => {
  blurRemoved.value = true;
};
</script>

<template>
  <span
    v-if="fill"
    style="
      position: relative;
      overflow: hidden;
      display: block;
      width: 100%;
      height: 100%;
    "
  >
    <img
      :alt="alt"
      :src="resolvedSrc"
      :srcset="srcSet"
      :sizes="resolvedSizes"
      :loading="resolvedLoading"
      :class="className"
      :style="imgStyle"
      :fetchpriority="resolvedFetchPriority"
      decoding="async"
      @load="handleLoad"
    />
  </span>

  <img
    v-else
    :alt="alt"
    :src="resolvedSrc"
    :srcset="srcSet"
    :sizes="resolvedSizes"
    :width="width"
    :height="height"
    :loading="resolvedLoading"
    :class="className"
    :style="imgStyle"
    :fetchpriority="resolvedFetchPriority"
    decoding="async"
    @load="handleLoad"
  />
</template>

// src/frontend/react/components/Image.tsx
import {
  buildOptimizedUrl,
  generateSrcSet,
  DEFAULT_QUALITY,
} from "../../shared/imageUtils";

type ImageProps = {
  src: string;
  alt: string;
  width?: number;
  height?: number;
  fill?: boolean;
  quality?: number;
  sizes?: string;
  unoptimized?: boolean;
  loading?: "lazy" | "eager";
  priority?: boolean;
  className?: string;
};

const resolveSource = (
  src: string,
  unoptimized: boolean | undefined,
  width: number | undefined,
  quality: number,
) => {
  if (unoptimized) return src;
  if (!width) return buildOptimizedUrl(src, 0, quality);

  return buildOptimizedUrl(src, width, quality);
};

export const Image = ({
  alt,
  className,
  fill,
  height,
  loading,
  priority,
  quality = DEFAULT_QUALITY,
  sizes,
  src,
  unoptimized,
  width,
}: ImageProps) => {
  const resolvedSrc = resolveSource(src, unoptimized, width, quality);

  const srcSet = unoptimized ? undefined : generateSrcSet(src, width, sizes);

  const resolvedSizes = sizes ?? (fill ? "100vw" : undefined);
  const resolvedLoading = priority ? "eager" : (loading ?? "lazy");
  const resolvedFetchPriority = priority ? "high" : undefined;

  const imgStyle: Record<string, string | number> = {
    color: "transparent",
    ...(fill
      ? {
          height: "100%",
          inset: 0,
          objectFit: "cover",
          position: "absolute",
          width: "100%",
        }
      : {}),
  };

  const preloadLink = priority ? (
    <link
      as="image"
      href={resolvedSrc}
      imageSizes={resolvedSizes}
      imageSrcSet={srcSet}
      rel="preload"
    />
  ) : null;

  const imgElement = (
    <img
      alt={alt}
      className={className}
      decoding="async"
      fetchPriority={resolvedFetchPriority}
      height={fill ? undefined : height}
      loading={resolvedLoading}
      sizes={resolvedSizes}
      src={resolvedSrc}
      srcSet={srcSet}
      style={imgStyle}
      width={fill ? undefined : width}
    />
  );

  if (fill) {
    return (
      <>
        {preloadLink}
        <span
          style={{
            display: "block",
            height: "100%",
            overflow: "hidden",
            position: "relative",
            width: "100%",
          }}
        >
          {imgElement}
        </span>
      </>
    );
  }

  return (
    <>
      {preloadLink}
      {imgElement}
    </>
  );
};
