// src/frontend/svelte/components/Image.svelte
<script lang="ts">
  import {
    buildOptimizedUrl,
    generateSrcSet,
    generateBlurSvg,
    DEFAULT_QUALITY,
  } from "../../shared/imageUtils";

  type ImageProps = {
    src: string;
    alt: string;
    width?: number;
    height?: number;
    fill?: boolean;
    quality?: number;
    sizes?: string;
    unoptimized?: boolean;
    loading?: "lazy" | "eager";
    priority?: boolean;
    placeholder?: "blur" | "empty" | string;
    blurDataURL?: string;
    className?: string;
  };

  let {
    src,
    alt,
    width,
    height,
    fill,
    quality = DEFAULT_QUALITY,
    sizes,
    unoptimized,
    loading,
    priority,
    placeholder,
    blurDataURL,
    className,
  }: ImageProps = $props();

  const resolvedSrc = $derived.by(() => {
    if (unoptimized) return src;
    if (!width) return buildOptimizedUrl(src, 0, quality);

    return buildOptimizedUrl(src, width, quality);
  });

  const srcSet = $derived(
    unoptimized
      ? undefined
      : generateSrcSet(src, width, sizes, undefined, undefined),
  );

  const resolvedSizes = $derived(sizes ?? (fill ? "100vw" : undefined));
  const resolvedLoading = $derived(priority ? "eager" : (loading ?? "lazy"));
  const resolvedFetchPriority = $derived(priority ? "high" : undefined);

  const hasBlur = $derived(
    placeholder === "blur" ||
      (typeof placeholder === "string" &&
        placeholder !== "empty" &&
        placeholder.startsWith("data:")),
  );

  const blurBackground = $derived.by(() => {
    if (!hasBlur) return undefined;
    if (
      typeof placeholder === "string" &&
      placeholder !== "blur" &&
      placeholder.startsWith("data:")
    ) {
      return generateBlurSvg(placeholder);
    }
    if (blurDataURL) return generateBlurSvg(blurDataURL);

    return undefined;
  });

  const imgStyle = $derived.by(() => {
    const parts: string[] = ["color:transparent"];
    if (blurBackground) {
      parts.push(`background-image:${blurBackground}`);
      parts.push("background-size:cover");
      parts.push("background-position:center");
      parts.push("background-repeat:no-repeat");
    }
    if (fill) {
      parts.push("position:absolute");
      parts.push("height:100%");
      parts.push("width:100%");
      parts.push("inset:0");
      parts.push("object-fit:cover");
    }

    return parts.join(";");
  });

  const handleLoad = (event: Event) => {
    if (blurBackground) {
      const target = event.target;
      if (target instanceof HTMLImageElement) {
        target.style.backgroundImage = "none";
      }
    }
  };
</script>

{#if fill}
  <span
    style="position:relative;overflow:hidden;display:block;width:100%;height:100%"
  >
    <img
      {alt}
      src={resolvedSrc}
      srcset={srcSet}
      sizes={resolvedSizes}
      loading={resolvedLoading}
      class={className}
      style={imgStyle}
      fetchpriority={resolvedFetchPriority}
      decoding="async"
      onload={handleLoad}
    />
  </span>
{:else}
  <img
    {alt}
    src={resolvedSrc}
    srcset={srcSet}
    sizes={resolvedSizes}
    {width}
    {height}
    loading={resolvedLoading}
    class={className}
    style={imgStyle}
    fetchpriority={resolvedFetchPriority}
    decoding="async"
    onload={handleLoad}
  />
{/if}

// src/frontend/vue/components/Image.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import {
  buildOptimizedUrl,
  generateSrcSet,
  generateBlurSvg,
  DEFAULT_QUALITY,
} from "../../shared/imageUtils";

type ImageProps = {
  src: string;
  alt: string;
  width?: number;
  height?: number;
  fill?: boolean;
  quality?: number;
  sizes?: string;
  unoptimized?: boolean;
  loading?: "lazy" | "eager";
  priority?: boolean;
  placeholder?: "blur" | "empty" | string;
  blurDataURL?: string;
  className?: string;
};

const props = withDefaults(defineProps<ImageProps>(), {
  quality: DEFAULT_QUALITY,
  loading: "lazy",
});

const blurRemoved = ref(false);

const resolvedSrc = computed(() => {
  if (props.unoptimized) return props.src;
  if (!props.width) return buildOptimizedUrl(props.src, 0, props.quality);

  return buildOptimizedUrl(props.src, props.width, props.quality);
});

const srcSet = computed(() =>
  props.unoptimized
    ? undefined
    : generateSrcSet(props.src, props.width, props.sizes, undefined, undefined),
);

const resolvedSizes = computed(
  () => props.sizes ?? (props.fill ? "100vw" : undefined),
);
const resolvedLoading = computed(() =>
  props.priority ? "eager" : props.loading,
);
const resolvedFetchPriority = computed(() =>
  props.priority ? "high" : undefined,
);

const hasBlur = computed(
  () =>
    props.placeholder === "blur" ||
    (typeof props.placeholder === "string" &&
      props.placeholder !== "empty" &&
      props.placeholder.startsWith("data:")),
);

const blurBackground = computed(() => {
  if (!hasBlur.value || blurRemoved.value) return undefined;
  if (
    typeof props.placeholder === "string" &&
    props.placeholder !== "blur" &&
    props.placeholder.startsWith("data:")
  ) {
    return generateBlurSvg(props.placeholder);
  }
  if (props.blurDataURL) return generateBlurSvg(props.blurDataURL);

  return undefined;
});

const imgStyle = computed(() => {
  const base: Record<string, string | number> = { color: "transparent" };
  if (blurBackground.value) {
    base.backgroundImage = blurBackground.value;
    base.backgroundSize = "cover";
    base.backgroundPosition = "center";
    base.backgroundRepeat = "no-repeat";
  }
  if (props.fill) {
    base.height = "100%";
    base.inset = "0";
    base.objectFit = "cover";
    base.position = "absolute";
    base.width = "100%";
  }

  return base;
});

const handleLoad = () => {
  blurRemoved.value = true;
};
</script>

<template>
  <span
    v-if="fill"
    style="
      position: relative;
      overflow: hidden;
      display: block;
      width: 100%;
      height: 100%;
    "
  >
    <img
      :alt="alt"
      :src="resolvedSrc"
      :srcset="srcSet"
      :sizes="resolvedSizes"
      :loading="resolvedLoading"
      :class="className"
      :style="imgStyle"
      :fetchpriority="resolvedFetchPriority"
      decoding="async"
      @load="handleLoad"
    />
  </span>

  <img
    v-else
    :alt="alt"
    :src="resolvedSrc"
    :srcset="srcSet"
    :sizes="resolvedSizes"
    :width="width"
    :height="height"
    :loading="resolvedLoading"
    :class="className"
    :style="imgStyle"
    :fetchpriority="resolvedFetchPriority"
    decoding="async"
    @load="handleLoad"
  />
</template>
