// src/frontend/react/components/Nav.tsx
export const Nav = () => (
  <header>
    <a className="logo" href="/">
      <img alt="AbsoluteJS" height={24} src="/assets/png/absolutejs-temp.png" />
      AbsoluteJS
    </a>
    <nav>
      <a className="active" href="/">
        React
      </a>
      <a href="/svelte">Svelte</a>
      <a href="/vue">Vue</a>
      <a href="/angular">Angular</a>
      <a href="/html">HTML</a>
      <a href="/htmx">HTMX</a>
    </nav>
  </header>
);

// src/frontend/vue/components/Nav.vue
<script setup lang="ts">
// Nav component — no props needed
</script>

<template>
  <header>
    <a class="logo" href="/">
      <img alt="AbsoluteJS" height="24" src="/assets/png/absolutejs-temp.png" />
      AbsoluteJS
    </a>
    <nav>
      <a href="/">React</a>
      <a href="/svelte">Svelte</a>
      <a class="active" href="/vue">Vue</a>
      <a href="/angular">Angular</a>
      <a href="/html">HTML</a>
      <a href="/htmx">HTMX</a>
    </nav>
  </header>
</template>
